# https://taskfile.dev

version: "3"

vars:
  # builtin_plugins:
  #   sh: ls ./crates/plugins
  builtin_plugins: |
    rustdeck-media
    rustdeck-system
    rustdeck-obs

tasks:
  mkdir:
    run: when_changed
    cmd: mkdir -p {{.PATH}}
    requires:
      vars: [PATH]

  build_rust_plugin:
    vars:
      FILE:
        sh: echo {{.PACKAGE}} | sed 's/-/_/' # Rust replaces hyphens with underscores in binaries' names
      ARGS: '{{ .ARGS | default "" }}'
      DEST: '{{ .DEST | default "./plugins" }}'
    cmds:
      - task: mkdir
        vars:
          PATH: "{{.DEST}}"
      - cargo build --package {{.PACKAGE}} {{.ARGS}}
      - cmd: cp -pf ./target/debug/lib{{.FILE}}.so {{.DEST}}/{{.FILE}}.deckplugin
        platforms: [linux]
      - cmd: cp -pf ./target/debug/{{.FILE}}.dll {{.DEST}}/{{.FILE}}.deckplugin
        platforms: [windows]
    requires:
      vars: [PACKAGE, ARGS, DEST]

  build_example_plugin:
    cmds:
      - task: build_rust_plugin
        vars: { PACKAGE: sample_plugin }

  build_example_c_plugin:
    cmds:
      - mkdir -p ./plugins
      - gcc -fpic ./examples/plugins/sample_c_plugin/main.c -shared -o ./plugins/sample_c_plugin.deckplugin

  build_builtin_plugins:
    vars:
      ARGS: '{{ .ARGS | default "" }}'
      DEST: '{{ .DEST | default "./plugins" }}'
    cmds:
      - for: { var: builtin_plugins }
        task: build_rust_plugin
        vars:
          PACKAGE: "{{.ITEM}}"
          DEST: "{{.DEST}}"
          ARGS: "{{.ARGS}}"
    requires:
      vars: [ARGS, DEST]

  package:
    cmds:
      - rm -rf ./dist

      - task: build_builtin_plugins
        vars:
          DEST: ./dist/pack/plugins
          ARGS: --release

      - cargo build --package rustdeck --release --features portable
      - cmd: cp ./target/release/rustdeck ./dist/pack/rustdeck
        platforms: [linux]
      - cmd: cp ./target/release/rustdeck.exe ./dist/pack/rustdeck.exe
        platforms: [windows]

      - 7z a -tzip -r ./dist/rustdeck.zip -w ./dist/pack/*

  mock_config:
    deps:
      - build_example_plugin
      - build_example_c_plugin
      - task: build_builtin_plugins

    cmds:
      - mkdir -p ./icons/
      - cp -r ./tests/test_resources/icons/ -t .
      - cp ./tests/test_resources/config.json ./config.json

  clean:
    cmds:
      - rm -rf ./dist
      - rm -rf ./icons
      - rm -rf ./plugins
      - rm -f  ./config.json

  reset:
    deps: [clean]
    cmds:
      - rm -rf ./target

  run_test:
    deps: [mock_config]
    cmds:
      - cargo run --package rustdeck
