# https://taskfile.dev

version: "3"

tasks:
  plugins_dir:
    cmd: mkdir -p ./plugins/
    generates:
      - ./plugins/
    status:
      - test -d directory

  build_example_plugin:
    deps: [plugins_dir]
    cmds:
      - cargo build --package sample_plugin
      - cmd: cp -pf ./target/debug/libsample_plugin.so ./plugins/sample_plugin.deckplugin
        platforms: [linux]
      - cmd: cp -pf ./target/debug/sample_plugin.dll ./plugins/sample_plugin.deckplugin
        platforms: [windows]

  build_example_c_plugin:
    deps: [plugins_dir]
    cmds:
      - gcc ./examples/plugins/sample_c_plugin/main.c -shared -o ./plugins/sample_c_plugin.deckplugin

  build_media_plugin:
    deps: [plugins_dir]
    cmds:
      - cargo build --package rustdeck-media
      - cmd: cp -pf ./target/debug/librustdeck_media.so ./plugins/rustdeck_media.deckplugin
        platforms: [linux]
      - cmd: cp -pf ./target/debug/rustdeck_media.dll ./plugins/rustdeck_media.deckplugin
        platforms: [windows]

  package:
    cmds:
      - mkdir -p ./dist/pack/plugins

      - cargo build --package rustdeck-media --release
      - cargo build --package rustdeck       --release --features portable

      - cmd: cp ./target/release/rustdeck ./dist/pack/rustdeck
        platforms: [linux]
      - cmd: cp ./target/release/rustdeck.exe ./dist/pack/rustdeck.exe
        platforms: [windows]

      - cmd: cp ./target/release/librustdeck_media.so ./dist/pack/plugins/rustdeck_media.deckplugin
        platforms: [linux]
      - cmd: cp ./target/release/rustdeck_media.dll ./dist/pack/plugins/rustdeck_media.deckplugin
        platforms: [windows]

      - 7z a -tzip -r ./dist/rustdeck.zip -w ./dist/pack/*

  mock_config:
    deps:
      - build_example_plugin
      - build_example_c_plugin
      - build_media_plugin

    cmds:
      - mkdir -p ./icons/
      - cp -r ./tests/test_resources/icons/ -t .
      - cp ./tests/test_resources/config.json ./config.json

  clean:
    cmds:
      - rm -rf ./dist
      - rm -rf ./icons
      - rm -rf ./plugins
      - rm -f  ./config.json

  run_test:
    deps: [mock_config]
    cmds:
      - cargo run --package rustdeck
